### ISSUE TITLE
Add field "id" in every feature

### ISSUE THREAD

**Issue by sumartoyo** [ans-4175/peta-indonesia-geojson#2]
Every feature should have field "id" so we can get the feature by ID. For example, in Google Maps API we call `maps.data.getFeatureById(ID)`. Reference [https://tools.ietf.org/html/rfc7946#page-11](https://tools.ietf.org/html/rfc7946#page-11).

**Comment by ans-4175** [comment]
Closed from this PR
https://github.com/ans-4175/peta-indonesia-geojson/pull/3
